name: Build OpenCentauri FW

on:
  workflow_call:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FW_VER: 1.1.40

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt install -y bsdiff
      
      - name: Download firmware
        run: |
          ./fwdl.sh $FW_VER

      - name: build patched firmware
        run: |
          rm ./oc-patches/patch_config
          cp ./firmware-editions/patched ./oc-patches/patch_config
          ./build.sh $FW_VER
          cp update/update.swu /tmp/update.swu

      - name: build klipper-pi firmware
        run: |
          rm ./oc-patches/patch_config
          cp ./firmware-editions/klipper-pi ./oc-patches/patch_config
          ./build.sh $FW_VER
          cp update/update.swu /tmp/klipper-pi.swu
      
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            update.swu
            klipper-pi.swu